import type { ParsedJob, Ring } from '../src/core/types';
import { parseGcode } from '../src/core/gcode';

export const rectangle = (x: number, y: number, w: number, h: number): Ring => [
  { x, y }, { x: x + w, y }, { x: x + w, y: y + h }, { x, y: y + h },
];

export function fixtureSource(absoluteE = false) {
  return `; generated by PrusaSlicer 2.9.6 on a test machine
; café: UTF-8 preservation fixture
G21
G90
${absoluteE ? 'M82' : 'M83'}
G92 E0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 X20 Y20 Z0.2 F1200
;TYPE:External perimeter
;WIDTH:0.48
G1 X40 Y20 E1
G1 X40 Y40 E${absoluteE ? 2 : 1}
G1 X20 Y40 E${absoluteE ? 3 : 1}
G1 X20 Y20 E${absoluteE ? 4 : 1}
;LAYER_CHANGE
;Z:0.4
G1 Z0.4
; prusaslicer_config = begin
; bed_shape = 0x0,200x0,200x200,0x200
; gcode_flavor = klipper
; first_layer_height = 0.2
; first_layer_extrusion_width = 0.48
; first_layer_speed = 20
; filament_diameter = 1.75
; extrusion_multiplier = 0.95
; retract_length = 0.8
; retract_speed = 35
; deretract_speed = 30
; travel_speed = 150
; travel_speed_z = 10
; retract_lift = 0.4
; prusaslicer_config = end
`;
}
export const fixtureJob = (): ParsedJob => parseGcode(fixtureSource());
